delayfruit/cart/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^cart/$', views.cart),
    url(r'^add_(\d+)_(\d+)/$', views.add),
    url(r'^edit_(\d+)_(\d+)/$', views.edit),
    url(r'^del_(\d+)/$', views.delete)
]

delayfruit/delayfruit/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('goods.urls')),
    url(r'^', include('ttss.urls')),
    url(r'^', include('cart.urls')),
    url(r'^', include('order.urls')),
    url(r'^tinymce$', include('tinymce.urls')),
    url(r'^search/$', include('haystack.urls')),

]

delayfruit/order/models.py
from django.db import models
import sys
sys.path.append('..')
from ttss.models import UserInfo
from goods.models import GoodsInfo
# Create your models here.


class OrderInfo(models.Model):
    ouser = models.ForeignKey(UserInfo, related_name='orderuser')
    ostate = models.IntegerField(default=0)
    odate = models.DateTimeField(auto_now=True)
    oprice = models.DecimalField(max_digits=10, decimal_places=2)
    # class Meta(object):
    #     db_table = 'order'


class OrderDetails(models.Model):
    order = models.ForeignKey(OrderInfo)
    goods = models.ForeignKey(GoodsInfo)
    count = models.IntegerField()
    price = models.IntegerField()

delayfruit/templates/df_user/login.html
{% extends 'base.html' %}
{% block head %}
	<script>
		$(function(){
		    name_error = false;
		    pass_error = false;


			{% if error_name != None %}
		    if( {{ error_name }} ==1){
		        $('.user_error').html('用户名错误').show()
			}
			if({{ error_pw }}==1){
		        $('.pwd_error').html('密码错误').show()
			}
			{% endif %}

			 if($('.ischeck').is(':checked')){
			    	$('.ischeck').val(1)
			 }
				else{
					$('.ischeck').val(0)
			 }
			$('.ischeck').click(function(){
			    if($('.ischeck').is(':checked')){
			    	$('.ischeck').val(1)
				}
				else{
					$('.ischeck').val(0)
				}
			})

			function checkname(){
				if($name_input.val() == ''){
			        $('.user_error').html('error_name').show();
					name_error = true;
				}
				else{
					$('.user_error').hide();
					name_error = false;
				}
			}
			function checkpass(){
				if($pass_input.val() == ''){
			        $('.pwd_error').html('error_pass').show();
			        pass_error = true;
				}
				else{
			         $('.pwd_error').hide();
			         pass_error = false;
				}
			}

			$name_input = $('.name_input')
			$pass_input = $('.pass_input')

			$name_input.blur(function(){
				checkname()
			})
			$pass_input.blur(function(){
				checkpass()
			})
			$('.loginform').submit(function(){
			    checkname();
			    checkpass();
			    if(pass_error == false && name_error == false){
			        return true;
				}
				else{
			        return false;
				}
			})
		})
	</script>
{% endblock head  %}
{% block body %}
	<div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>l
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" action="/user/check_u/" class="loginform">
						{% csrf_token %}
						<input type="text" name="username" value="{{ uname }}" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="{{ pw }}" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="checked"  checked="checked"  class="ischeck">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}
{% block footer %}
{% include 'footer.html'%}
{% endblock footer %}

delayfruit/templates/df_user/register.html
{% extends 'base.html' %}
{% block title %}
	<title>天天生鲜-注册</title>
{% endblock title %}
{% block head %}
	<script type="text/javascript" src="/static/js/register.js"></script>
{% endblock head %}
{%  block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/user_add/" method="post">
					{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{%  endblock body %}
{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

delayfruit/templates/df_user/user_center_info.html
{% extends 'goods_base.html' %}
{% block title %}
	<title>天天生鲜-个人信息</title>
{% endblock title %}
{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" class="active">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>18210569700</li>
							<li><span>联系方式：</span>18210569700</li>
							<li><span>联系地址：</span>北京市昌平区</li>			
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
					{% for item in goods %}
						<li>
							<a href="/{{item.id}}/"><img src="/static/images/goods/goods003.jpg"></a>
							<h4><a href="{{item.id}}">{{item.gtitle}}</a></h4>
							<div class="operate">
								<span class="prize">￥{{item.gprice}}</span>
								<span class="unit">{{item.price}}/{{item.gunti}}</span>
								<a href="#" class="add_goods" title="加入购物车"></a>
							</div>
						</li>
					{%empty%}
						你还没有浏览快去吧
					{% endfor%}

					</ul>
				</div>
		</div>
	</div>
{% endblock body %}
{% block footer %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock footer %}

delayfruit/templates/df_user/user_center_order.html
{% extends 'goods_base.html' %}
{% block header %}
	{{block.super}}
{% endblock header %}
{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" >· 个人信息</a></li>
				<li><a href="/user/order/" class="active" >· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
			{% for order in page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{order.odate}}</li>
					<li class="col02">订单号：{{order.id}}</li>
					<li class="col02 stress">未支付</li>		
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								{% for orderdeatil in order.orderdetails_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/images/{{orderdeatil.goods.gimg}}"></li>
									<li class="col02">{{orderdeatil.goods.gtitle}}<em>{{orderdeatil.goods.gprice}}元/{{orderdeatil.goods.gunit}}</em></li>
									<li class="col03">{{orderdeatil.count}}</li>
									<li class="col04">{{orderdeatil.price}}元</li>
								</ul>
								{% endfor %}
							</td>
							<td width="15%">{{order.oprice}}元</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="/orders/?order_id={{order.id}}" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
			{% endfor %}
				<div class="pagenation">

					{% if page.has_previous %}
						<a href="/user/order{{page.previous_page_number}}/"><上一页</a>
					{% endif %}
					{% for pindex in p_list %}
					{% if pindex == page.number %}
					<a href="/user/order{{pindex}}/" class="active">{{pindex}}</a>
					{% else %}
					<a href="/user/order{{pindex}}/">{{pindex}}</a>
					{% endif %}
					{% endfor %}
					{% if page.has_next %}
						<a href="/user/order{{page.next_page_number}}/">下一页></a>
					{% endif %}

				</div>
		</div>
	</div>


{% endblock body %}

delayfruit/templates/df_user/user_center_site.html
{% extends 'goods_base.html' %}
{% block header %}
	{{ block.super }}
{% endblock header %}
{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" >· 个人信息</a></li>
				<li><a href="/user/order/"  >· 全部订单</a></li>
				<li><a href="/user/site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="/user/site/">
						{%  csrf_token　%}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou" value="{{info.ushou}}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address"  >{{info.uaddress}}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="uyoubian" value="{{info.uyoubian}}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone" value="{{info.uphone}}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock body %}